FROM python:3.7.9

RUN sh -c "$(curl -sSfL https://release.solana.com/v1.7.0/install)"
ENV PATH="/root/.local/share/solana/install/active_release/bin:${PATH}"
RUN solana config set --url https://api.devnet.solana.com
RUN apt-get update && apt-get install vim -y
COPY ./asset_issuer ./asset_issuer
WORKDIR ./asset_issuer
RUN pip install -r requirements.txt
ENTRYPOINT python app.py